spring:
  application:
    name: "activiti-practice"
  profiles:
    active: dev
server:
  port: 8081
  tomcat:
    threads:
      max: 200
    accept-count: 1000
  servlet:
    context-path: /activiti



test-config:
  name: luffy
  password: 123456
hello:
  msg: "helloWorld"
