server:
  port: 8083
  tomcat:
    threads:
      max: 200
    accept-count: 1000
  servlet:
    context-path: /activiti
spring:
  application:
    name: "activiti-practice-test"


test-config:
  name: luffy-test
  password: 135246
